# Generated by Django 2.0.1 on 2018-06-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruleresult',
            old_name='date',
            new_name='data',
        ),
    ]
