# Generated by Django 2.0.1 on 2018-06-13 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salt',
            name='uid',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='salt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ad.Salt'),
        ),
    ]
