# Generated by Django 2.0.1 on 2018-06-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0005_auto_20180613_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salt',
            name='value',
            field=models.CharField(max_length=256),
        ),
    ]
