# Generated by Django 2.0.1 on 2018-06-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0006_auto_20180613_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salt',
            name='value',
            field=models.BinaryField(max_length=256),
        ),
    ]
