# Generated by Django 2.0.1 on 2018-06-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0007_auto_20180613_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleindex',
            name='warning',
            field=models.BooleanField(default=False),
        ),
    ]
