# Generated by Django 2.0.1 on 2018-06-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0008_ruleindex_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleindex',
            name='warning',
            field=models.IntegerField(default=0),
        ),
    ]
