# Generated by Django 2.0.1 on 2018-06-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0010_auto_20180621_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleindex',
            name='name',
            field=models.IntegerField(choices=[(0, '无响应'), (1, 'CPU使用率'), (2, '内存使用率'), (3, '磁盘Inode'), (4, '磁盘空间'), (5, '磁盘IOPS'), (6, '发送流量'), (7, '连接数'), (8, '接收流量'), (9, '端口检查')]),
        ),
    ]
