# Generated by Django 2.0.1 on 2018-07-26 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0012_ruleindex_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='user_group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ad.UserGroup'),
        ),
    ]
